---
project:
    type: website
website:
    title: "Robot Genome"
    navbar:
        search: true
        left:
            - href: index.qmd
              text: Home
            - text: About
              href: about.qmd
            - text: "Projects"
              menu:
                  - text: "WGS Upcaling"
                    href: projects/wgs_upscale/wgs_upscaling_bioinf.qmd
                  - text: "Workflow Tracker"
                    href: projects/workflow_tracker/index.html
format:
    html:
        theme: Journal
        grid:
            sidebar-width: 100px
            body-width: 1000px
        css: styles.css
        toc: true
