---
project:
    type: website
website:
    favicon: logo.png
    title: "Robot Genome"
    margin-header: |
        ![](/logo_square.png)
    navbar:
        search: true
        left:
            - href: index.qmd
              text: Home
            - text: About
              href: about.qmd
            - text: "Projects"
              menu:
                  - text: "WGS Upcaling"
                    href: projects/wgs_upscale/wgs_upscaling_bioinf.qmd
                  - text: "Workflow Tracker"
                    href: projects/workflow_tracker/index.html
                  - text: "UUID"
                    href: projects/UUID/uuid.qmd
                  - text: "PGDIS 2024"
                    href: projects/PGDIS2024/pgdis2024.qmd
format:
    html:
        theme:
            light: Journal
            dark: Superhero
        grid:
            sidebar-width: 100px
            body-width: 1100px
            margin-width: 300px
        css: styles.css
        toc: true
execute:
    freeze: true
